language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
services:
  - postgresql
before_script:
  - psql -c 'create database myapp_test;' -U postgres
before_install:
  - sudo apt-get install python-lxml
install:
# OpenERP does not specify the version of pyparsing and the later
# version only work with py3k
  - pip install "pyparsing==1.5.7"
  - pip install flake8
  - ./install_nightly.sh
  - pip install distribute
  - python setup.py install
script:
  - python setup.py test_on_travis
  - flake8 .
notifications:
  email:
    - ci-notify@openlabs.co.in
